/*
 * JSP generated by Resin Professional 3.1.10 (built Tue, 23 Feb 2010 02:58:10 PST)
 */

package _jsp._web_22dinf._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _departmentinfo__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html");
    response.setCharacterEncoding("UTF-8");
    request.setCharacterEncoding("UTF-8");
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      _caucho_expr_0.print(out, _jsp_env, false);
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _caucho_expr_1.print(out, _jsp_env, false);
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _caucho_expr_2.print(out, _jsp_env, false);
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_3.print(out, _jsp_env, false);
      out.write(_jsp_string4, 0, _jsp_string4.length);
      _caucho_expr_4.print(out, _jsp_env, false);
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_5.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7394374792971521532L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.userinfo.userId}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.userinfo.userName}");
    _caucho_expr_2 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.userinfo.userEmail}");
    _caucho_expr_3 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.userinfo.state == true?\"\u5ba1\u6838\":\"\u672a\u5ba1\u6838\"}");
    _caucho_expr_4 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.userinfo.isManager == true?\"\u7ba1\u7406\u5458\":\"\u666e\u901a\u7528\u6237\"}");
    _caucho_expr_5 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${sessionScope.userinfo.workerId}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/jsp/departmentInfo.jsp"), 6606196240594958993L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;
  private static com.caucho.el.Expr _caucho_expr_2;
  private static com.caucho.el.Expr _caucho_expr_3;
  private static com.caucho.el.Expr _caucho_expr_4;
  private static com.caucho.el.Expr _caucho_expr_5;

  private final static char []_jsp_string5;
  private final static char []_jsp_string0;
  private final static char []_jsp_string6;
  private final static char []_jsp_string4;
  private final static char []_jsp_string1;
  private final static char []_jsp_string2;
  private final static char []_jsp_string3;
  static {
    _jsp_string5 = " \r\n        </td>\r\n      </tr>\r\n      <tr>\r\n        <td align=\"right\"><strong>\u5458\u5de5\u7f16\u53f7:</strong></td>\r\n        <td align=\"left\">".toCharArray();
    _jsp_string0 = "\r\n<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n<html>\r\n<head>\r\n<title>\u8d26\u53f7\u4fe1\u606f</title>\r\n<link rel=\"stylesheet\" href=\"Styles/style.css\" type=\"text/css\">\r\n</head>\r\n<body style=\"background-color:#2F6FA1\">\r\n<p align=\"center\" class=\"title1\">\u8d26\u53f7\u4fe1\u606f</p>\r\n<div style=\"background-image:url(image/login-top.JPG); margin:0px auto 0px; width:400px; height:20px;\"></div>\r\n<div style=\"background-color:#FFFFFF; margin:0px auto 0px; width:400px;\">\r\n  <form action=\"userUpdateAccount.jsp\" method=\"post\">\r\n  <input type=\"hidden\" name=\"action\" value=\"update\">\r\n    <table align=\"center\" cellspacing=\"10\">\r\n      <tr>\r\n        <td align=\"right\"><strong>\u7528\u6237\u7f16\u53f7:</strong></td>\r\n        <td align=\"left\">".toCharArray();
    _jsp_string6 = "\r\n        </td>\r\n      </tr>     \r\n      <tr align=\"center\">\r\n        <td colspan=\"2\"><input type=\"submit\" id=\"submit\" value=\"\u4fee\u6539\" />\r\n          <input type=\"button\" value=\"\u8fd4\u56de\" onclick=\"javascript:history.back()\" /></td>\r\n      </tr>\r\n    </table>\r\n  </form>\r\n</div>\r\n</body>\r\n</html>\r\n".toCharArray();
    _jsp_string4 = " \r\n        </td>\r\n      </tr>\r\n      <tr>\r\n        <td align=\"right\"><strong>\u7528\u6237\u89d2\u8272:</strong></td>\r\n        <td align=\"left\">".toCharArray();
    _jsp_string1 = "</td>\r\n      </tr>\r\n      <tr>\r\n        <td width=\"150\" align=\"right\"><strong>\u7528\u6237\u540d:</strong> </td>\r\n        <td width=\"200\" align=\"left\">".toCharArray();
    _jsp_string2 = "</td>\r\n      </tr>\r\n      <tr>\r\n        <td align=\"right\"><strong>Email:</strong></td>\r\n        <td align=\"left\">".toCharArray();
    _jsp_string3 = "</td>\r\n      </tr>\r\n      <tr>\r\n        <td align=\"right\"><strong>\u7528\u6237\u72b6\u6001:</strong></td>\r\n        <td align=\"left\">".toCharArray();
  }
}
