/*
 * JSP generated by Resin Professional 3.1.10 (built Tue, 23 Feb 2010 02:58:10 PST)
 */

package _jsp._web_22dinf._jsp;
import javax.servlet.*;
import javax.servlet.jsp.*;
import javax.servlet.http.*;

public class _login__jsp extends com.caucho.jsp.JavaPage
{
  private static final java.util.HashMap<String,java.lang.reflect.Method> _jsp_functionMap = new java.util.HashMap<String,java.lang.reflect.Method>();
  private boolean _caucho_isDead;
  
  public void
  _jspService(javax.servlet.http.HttpServletRequest request,
              javax.servlet.http.HttpServletResponse response)
    throws java.io.IOException, javax.servlet.ServletException
  {
    javax.servlet.http.HttpSession session = request.getSession(true);
    com.caucho.server.webapp.WebApp _jsp_application = _caucho_getApplication();
    javax.servlet.ServletContext application = _jsp_application;
    com.caucho.jsp.PageContextImpl pageContext = _jsp_application.getJspApplicationContext().allocatePageContext(this, _jsp_application, request, response, null, session, 8192, true, false);
    javax.servlet.jsp.PageContext _jsp_parentContext = pageContext;
    javax.servlet.jsp.JspWriter out = pageContext.getOut();
    final javax.el.ELContext _jsp_env = pageContext.getELContext();
    javax.servlet.ServletConfig config = getServletConfig();
    javax.servlet.Servlet page = this;
    response.setContentType("text/html; charset=GBK");
    request.setCharacterEncoding("GBK");
    org.springframework.web.servlet.tags.form.ErrorsTag _jsp_ErrorsTag_0 = null;
    try {
      out.write(_jsp_string0, 0, _jsp_string0.length);
      if (_jsp_ErrorsTag_0 == null) {
        _jsp_ErrorsTag_0 = new org.springframework.web.servlet.tags.form.ErrorsTag();
        _jsp_ErrorsTag_0.setPageContext(pageContext);
        _jsp_ErrorsTag_0.setParent((javax.servlet.jsp.tagext.Tag) null);
      }

      _jsp_ErrorsTag_0.setPath("name");
      javax.servlet.jsp.JspWriter _jsp_writer1 = out;
      try {
        int _jspEval2 = _jsp_ErrorsTag_0.doStartTag();
        _jsp_ErrorsTag_0.doEndTag();
      } catch (Throwable _jsp_exn_4) {
        pageContext.setWriter(_jsp_writer1);
        out = _jsp_writer1;
        _jsp_ErrorsTag_0.doCatch(_jsp_exn_4);
      } finally {
        _jsp_ErrorsTag_0.doFinally();
      }
      out.write(_jsp_string1, 0, _jsp_string1.length);
      _jsp_ErrorsTag_0.setPath("password");
      javax.servlet.jsp.JspWriter _jsp_writer6 = out;
      try {
        int _jspEval7 = _jsp_ErrorsTag_0.doStartTag();
        _jsp_ErrorsTag_0.doEndTag();
      } catch (Throwable _jsp_exn_9) {
        pageContext.setWriter(_jsp_writer6);
        out = _jsp_writer6;
        _jsp_ErrorsTag_0.doCatch(_jsp_exn_9);
      } finally {
        _jsp_ErrorsTag_0.doFinally();
      }
      out.write(_jsp_string2, 0, _jsp_string2.length);
      _jsp_ErrorsTag_0.setPath("passwordConfirm");
      javax.servlet.jsp.JspWriter _jsp_writer11 = out;
      try {
        int _jspEval12 = _jsp_ErrorsTag_0.doStartTag();
        _jsp_ErrorsTag_0.doEndTag();
      } catch (Throwable _jsp_exn_14) {
        pageContext.setWriter(_jsp_writer11);
        out = _jsp_writer11;
        _jsp_ErrorsTag_0.doCatch(_jsp_exn_14);
      } finally {
        _jsp_ErrorsTag_0.doFinally();
      }
      out.write(_jsp_string3, 0, _jsp_string3.length);
      _caucho_expr_0.print(out, _jsp_env, true);
      out.write(_jsp_string4, 0, _jsp_string4.length);
      _jsp_ErrorsTag_0.setPath("code");
      javax.servlet.jsp.JspWriter _jsp_writer16 = out;
      try {
        int _jspEval17 = _jsp_ErrorsTag_0.doStartTag();
        _jsp_ErrorsTag_0.doEndTag();
      } catch (Throwable _jsp_exn_19) {
        pageContext.setWriter(_jsp_writer16);
        out = _jsp_writer16;
        _jsp_ErrorsTag_0.doCatch(_jsp_exn_19);
      } finally {
        _jsp_ErrorsTag_0.doFinally();
      }
      out.write(_jsp_string5, 0, _jsp_string5.length);
      _caucho_expr_1.print(out, _jsp_env, false);
      out.write(_jsp_string6, 0, _jsp_string6.length);
      _caucho_expr_1.print(out, _jsp_env, true);
      out.write(_jsp_string7, 0, _jsp_string7.length);
    } catch (java.lang.Throwable _jsp_e) {
      pageContext.handlePageException(_jsp_e);
    } finally {
      if (_jsp_ErrorsTag_0 != null)
        _jsp_ErrorsTag_0.release();
      _jsp_application.getJspApplicationContext().freePageContext(pageContext);
    }
  }

  private java.util.ArrayList _caucho_depends = new java.util.ArrayList();

  public java.util.ArrayList _caucho_getDependList()
  {
    return _caucho_depends;
  }

  public void _caucho_addDepend(com.caucho.vfs.PersistentDependency depend)
  {
    super._caucho_addDepend(depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
  }

  public boolean _caucho_isModified()
  {
    if (_caucho_isDead)
      return true;
    if (com.caucho.server.util.CauchoSystem.getVersionId() != 7394374792971521532L)
      return true;
    for (int i = _caucho_depends.size() - 1; i >= 0; i--) {
      com.caucho.vfs.Dependency depend;
      depend = (com.caucho.vfs.Dependency) _caucho_depends.get(i);
      if (depend.isModified())
        return true;
    }
    return false;
  }

  public long _caucho_lastModified()
  {
    return 0;
  }

  public java.util.HashMap<String,java.lang.reflect.Method> _caucho_getFunctionMap()
  {
    return _jsp_functionMap;
  }

  public void init(ServletConfig config)
    throws ServletException
  {
    com.caucho.server.webapp.WebApp webApp
      = (com.caucho.server.webapp.WebApp) config.getServletContext();
    super.init(config);
    com.caucho.jsp.TaglibManager manager = webApp.getJspApplicationContext().getTaglibManager();
    manager.addTaglibFunctions(_jsp_functionMap, "sg", "http://www.springframework.org/tags/form");
    manager.addTaglibFunctions(_jsp_functionMap, "c", "http://java.sun.com/jsp/jstl/core");
    com.caucho.jsp.PageContextImpl pageContext = new com.caucho.jsp.PageContextImpl(webApp, this);
    _caucho_expr_0 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${message}");
    _caucho_expr_1 = com.caucho.jsp.JspUtil.createExpr(pageContext.getELContext(), "${randomNumbers}");
  }

  public void destroy()
  {
      _caucho_isDead = true;
      super.destroy();
  }

  public void init(com.caucho.vfs.Path appDir)
    throws javax.servlet.ServletException
  {
    com.caucho.vfs.Path resinHome = com.caucho.server.util.CauchoSystem.getResinHome();
    com.caucho.vfs.MergePath mergePath = new com.caucho.vfs.MergePath();
    mergePath.addMergePath(appDir);
    mergePath.addMergePath(resinHome);
    com.caucho.loader.DynamicClassLoader loader;
    loader = (com.caucho.loader.DynamicClassLoader) getClass().getClassLoader();
    String resourcePath = loader.getResourcePathSpecificFirst();
    mergePath.addClassPath(resourcePath);
    com.caucho.vfs.Depend depend;
    depend = new com.caucho.vfs.Depend(appDir.lookup("WEB-INF/jsp/login.jsp"), 4304680681291612522L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    depend = new com.caucho.vfs.Depend(mergePath.lookup("jar:file:/E:/\u7126\u70b9\u5b9e\u4e60\u5b66\u4e60\u8d44\u6599/\u6846\u67b6\u8d44\u6599/spring-framework-3.1.1.RELEASE-with-docs/spring-framework-3.1.1.RELEASE/dist/org.springframework.web.servlet-3.1.1.RELEASE.jar!/META-INF/spring-form.tld"), -7844667629652253265L, false);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, depend);
    com.caucho.jsp.JavaPage.addDepend(_caucho_depends, new com.caucho.make.ClassDependency(org.springframework.web.servlet.tags.form.ErrorsTag.class, 3291925833925675303L));
  }

  static {
    try {
    } catch (Exception e) {
      e.printStackTrace();
      throw new RuntimeException(e);
    }
  }
  private static com.caucho.el.Expr _caucho_expr_0;
  private static com.caucho.el.Expr _caucho_expr_1;

  private final static char []_jsp_string1;
  private final static char []_jsp_string3;
  private final static char []_jsp_string7;
  private final static char []_jsp_string2;
  private final static char []_jsp_string0;
  private final static char []_jsp_string4;
  private final static char []_jsp_string5;
  private final static char []_jsp_string6;
  static {
    _jsp_string1 = "</td>\r\n             </tr>\r\n             <tr>\r\n                 <td class=\"row1\">\u5bc6  \u7801:</td>\r\n                 <td><input type=\"password\" name=\"password\" /></td>\r\n                 <td>".toCharArray();
    _jsp_string3 = "</td>\r\n                 <td> ".toCharArray();
    _jsp_string7 = "\r\n					 </span>\r\n				 </td>\r\n             </tr> \r\n             <tfoot>\r\n             <tr>\r\n              <td><a href=\"#\" >\u4fee\u6539\u5bc6\u7801</a></td>\r\n              <td><a href=\"#\" >\u5feb\u901f\u6ce8\u518c</a></td>\r\n              <td><input id=\"login\" type=\"submit\" value=\"\u5feb\u901f\u767b\u5165\"/></td>\r\n             </tr>\r\n             </tfoot>\r\n          </tbody>\r\n      </table>\r\n	</form>\r\n  </div>\r\n   <script type=\"text/javascript\" src=\"/js/common/jquery-1.7.2.js\"></script>\r\n   <script type=\"text/javascript\" src=\"/js/identify.js\"></script>\r\n</body>\r\n</html>".toCharArray();
    _jsp_string2 = "</td>\r\n             </tr>\r\n            <tr>\r\n                 <td class=\"row1\">\u786e\u8ba4\u5bc6\u7801:</td>\r\n                 <td><input type=\"password\" name=\"passwordConfirm\" /></td>\r\n                 <td>".toCharArray();
    _jsp_string0 = "\r\n\r\n\r\n<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n<html>\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=GBK\">\r\n<title>\u7528\u6237\u767b\u5165</title>\r\n<link rel=\"stylesheet\" href=\"/css/table.css\" type=\"text/css\">\r\n</head>\r\n<body>\r\n<div id=\"side2\"><embed src=\"/music/dream.mp3\" autostart=true loop=true hidden=\"false\"/> </div>\r\n<div id=\"side1\">\r\n <img alt=\"\u80cc\u666f\u56fe\u7247\" src=\"/img/head2.jpg\">\r\n</div>\r\n<div  id=\"main\">\r\n	<form method=\"post\" action=\"/employee/result\">\r\n      <table>\r\n          <thead>\r\n             <tr><th colspan=\"3\">\u7528 \u6237 \u767b \u5165</th></tr>\r\n          </thead>\r\n          <tbody>\r\n             <tr>\r\n                 <td class=\"row1\">\u7528\u6237\u540d:</td>\r\n                 <td><input type=\"text\" name=\"name\"/></td>\r\n                 <td>".toCharArray();
    _jsp_string4 = "</td>\r\n             </tr>\r\n              <tr>\r\n                 <td class=\"row1\">\u9a8c\u8bc1\u7801:</td>\r\n                 <td><input id=\"icode\" type=\"text\" name=\"code\"/></td>\r\n                 <td>".toCharArray();
    _jsp_string5 = "	\r\n					<span id=\"codes\" data-code=\"".toCharArray();
    _jsp_string6 = "\">\r\n					   ".toCharArray();
  }
}
